"""empty message

Revision ID: 1eca902e8c30
Revises: 290f5a90d14c
Create Date: 2022-10-10 17:22:33.327619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eca902e8c30'
down_revision = '290f5a90d14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('the_shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('the_shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('the_shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('the_shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
