"""empty message

Revision ID: 290f5a90d14c
Revises: bba63760a4c4
Create Date: 2022-10-09 02:50:08.712643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '290f5a90d14c'
down_revision = 'bba63760a4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('the_shows', 'show_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('the_shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('the_shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('the_shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('the_shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('the_shows', 'show_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
